name: Post JSON File to Two URLs

jobs:
  post_json:
    name: Send JSON Data to Two URLs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://first-api-url.com" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://second-api-url.com" \
               -H "Content-Type: application/json" \
               -d @stream.json

